//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS_Web_22S1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competency_Qualification
    {
        public string QualCode { get; set; }
        public string NationalCompCode { get; set; }
        public string CompTypeCode { get; set; }
    
        public virtual Competency_Type Competency_Type { get; set; }
    }
}
