//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS_Web_22S1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRN_Session_Timetable
    {
        public string CRN { get; set; }
        public int TermCodeStart { get; set; }
        public int TermYearStart { get; set; }
        public int DayCode { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Room { get; set; }
        public string Building { get; set; }
        public string CampusCode { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual CRN_Detail CRN_Detail { get; set; }
        public virtual Day_Of_Week Day_Of_Week { get; set; }
        public virtual Term_Datetime Term_Datetime { get; set; }
    }
}
