//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS_Web_22S1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRN_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRN_Detail()
        {
            this.CRN_Session_Timetable = new HashSet<CRN_Session_Timetable>();
            this.Student_Grade = new HashSet<Student_Grade>();
        }
    
        public string CRN { get; set; }
        public string TafeCompCode { get; set; }
        public int TermCodeStart { get; set; }
        public int TermYearStart { get; set; }
        public int TermCodeEnd { get; set; }
        public int TermYearEnd { get; set; }
        public string SubjectCode { get; set; }
        public string CampusCode { get; set; }
        public string LecturerID { get; set; }
        public string DepartmentCode { get; set; }
        public System.DateTime FreezeDate { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual Competency Competency { get; set; }
        public virtual Department Department { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Term_Datetime Term_Datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRN_Session_Timetable> CRN_Session_Timetable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Grade> Student_Grade { get; set; }
    }
}
