//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS_Web_22S1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_tafesaspsEntities : DbContext
    {
        public db_tafesaspsEntities()
            : base("name=db_tafesaspsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campu> Campus { get; set; }
        public virtual DbSet<Competency> Competencies { get; set; }
        public virtual DbSet<Competency_Qualification> Competency_Qualification { get; set; }
        public virtual DbSet<Competency_Type> Competency_Type { get; set; }
        public virtual DbSet<CRN_Detail> CRN_Detail { get; set; }
        public virtual DbSet<CRN_Session_Timetable> CRN_Session_Timetable { get; set; }
        public virtual DbSet<Day_Of_Week> Day_Of_Week { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Lecturer> Lecturers { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Grade> Student_Grade { get; set; }
        public virtual DbSet<Student_Studyplan> Student_Studyplan { get; set; }
        public virtual DbSet<Studyplan_Qualification> Studyplan_Qualification { get; set; }
        public virtual DbSet<Studyplan_Subject> Studyplan_Subject { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Subject_Qualification> Subject_Qualification { get; set; }
        public virtual DbSet<Term_Datetime> Term_Datetime { get; set; }
    }
}
