//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS_Web_22S1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Studyplan
    {
        public string StudentID { get; set; }
        public string QualCode { get; set; }
        public int TermCodeStart { get; set; }
        public int TermYearStart { get; set; }
        public string EnrolmentType { get; set; }
    
        public virtual Qualification Qualification { get; set; }
        public virtual Student Student { get; set; }
        public virtual Term_Datetime Term_Datetime { get; set; }
    }
}
